module.exports = {
    Cards: [
    { 
        name:"Antoni Borgosz",
        Desc:"",
        Image:"img/AntoniBorgosz.jpg",
        Type:"com",
        Quality:"gold",
        Nation:"neutral",
        Power:7,
        func:function(){} 
    },
    { 
        name:"Tadeusz Piszkowski",
        Desc:"",
        Image:"img/TadeuszPiszkowski.jpg",
        Type:"com",
        Quality:"gold",
        Nation:"neutral",
        Power:8,
        func:function(){} 
    },
    { 
        name:"Paweł Kucharczyk",
        Desc:"",
        Image:"img/PawełKucharczyk.jpg",
        Type:"com",
        Quality:"gold",
        Nation:"inf",
        Power:9,
        func:function(){} 
    },
    { 
        name:"Dariusz Stefańczyk",
        Desc:"",
        Image:"img/DariuszStefańczyk.jpg",
        Type:"unit",
        Quality:"gold",
        Nation:"inf",
        Power:5,
        func:function(){} 
    },
    { 
        name:"Maciej Mendela",
        Desc:"",
        Image:"img/MaciejMendela.jpg",
        Type:"unit",
        Quality:"gold",
        Nation:"inf",
        Power:7,
        func:function(){} 
    },
    { 
        name:"Katarzyna Ślusarczyk",
        Desc:"",
        Image:"img/KatarzynaSlusarczyk.jpg",
        Type:"unit",
        Quality:"gold",
        Nation:"inf",
        Power:7,
        func:function(){} 
    },
    { 
        name:"Piotr Kędra",
        Desc:"",
        Image:"img/PiotrKedra.jpg",
        Type:"unit",
        Quality:"gold",
        Nation:"inf",
        Power:7,
        func:function(){} 
    },
   { 
        name:"Michał Ciborowski",
        Desc:"",
        Image:"img/Ciborowski.jpg",
        Type:"unit",
        Quality:"silver",
        Nation:"inf",
        Power:7,
        func:function(){} 
    },
    { 
        name:"Wacław Świdrak",
        Desc:"",
        Image:"img/Swidrak.jpg",
        Type:"unit",
        Quality:"silver",
        Nation:"inf",
        Power:7,
        func:function(){} 
    },
    { 
        name:"Andrzej Płachta",
        Desc:"",
        Image:"img/AndrzejPlachta.jpg",
        Type:"unit",
        Quality:"silver",
        Nation:"inf",
        Power:7,
        func:function(){} 
    },
    { 
        name:"Jacek Skibicki",
        Desc:"",
        Image:"img/JacekSkibicki.jpg",
        Type:"unit",
        Quality:"silver",
        Nation:"inf",
        Power:7,
        func:function(){} 
    },
    { 
        name:"Marek Łętocha",
        Desc:"",
        Image:"img/MarekLetocha.jpg",
        Type:"unit",
        Quality:"silver",
        Nation:"inf",
        Power:7,
        func:function(){} 
    },
    { 
        name:"Zdzisław Krawiec",
        Desc:"",
        Image:"img/ZdzislawKrawiec.jpg",
        Type:"unit",
        Quality:"silver",
        Nation:"inf",
        Power:7,
        func:function(){} 
    },
    { 
        name:"Olimpijczyk",
        Desc:"",
        Image:"img/Olimpijczyk.jpg",
        Type:"unit",
        Quality:"brown",
        Nation:"inf",
        Power:5,
        func:function(){} 
    },
    { 
        name:"Informatyczka",
        Desc:"",
        Image:"img/Informatyczka.jpg",
        Type:"unit",
        Quality:"brown",
        Nation:"inf",
        Power:7,
        func:function(){} 
    },
    { 
        name:"Programista",
        Desc:"",
        Image:"img/Programista.jpg",
        Type:"unit",
        Quality:"brown",
        Nation:"inf",
        Power:7,
        func:function(){} 
    },
    { 
        name:"Apple Boy",
        Desc:"",
        Image:"img/AppleBoy.jpg",
        Type:"unit",
        Quality:"brown",
        Nation:"inf",
        Power:7,
        func:function(){} 
    },
    { 
        name:"Systemowiec",
        Desc:"",
        Image:"img/Systemowiec.jpg",
        Type:"unit",
        Quality:"brown",
        Nation:"inf",
        Power:7,
        func:function(){} 
    },
    { 
        name:"Podrywacz",
        Desc:"",
        Image:"img/Podrywacz.jpg",
        Type:"unit",
        Quality:"brown",
        Nation:"inf",
        Power:7,
        func:function(){} 
    }
    ]
}